### ISSUE TITLE
Nuki Opener Support

### ISSUE THREAD

**Issue by dennisoderwald** [jghaanstra/nuki.homey#1]
Are you planning to support the Nuki Opener?

**Comment by jghaanstra** [comment]
When it becomes available in the HTTP Bridge API. You can vote for this feature on the Nuki developer forum here: https://developer.nuki.io/t/nuki-bridge-api-bell-ring-of-nuki-opener-as-trigger-for-callbacks/2557/13

**Comment by jghaanstra** [comment]
This has been added with release 1.3.0.
