### ISSUE TITLE
compose error 

### ISSUE THREAD

**Issue by Strike2001** [jghaanstra/nuki.homey#13]
![7BB72D1D-8620-47B0-AD66-456D4663DA7C](https://user-images.githubusercontent.com/5000021/94735653-62dd8200-036b-11eb-853c-2a9eaebd8ae4.jpeg)

**Comment by pfreguia** [comment]
Hello Strike2001,
In the master branch there is a work in progress for adding the German translation of the app. Now I fixed the error (the translator inserted a not allowed char) and you can run the app in the master branch. Anyway, you can find Nuki Direct v3.0.4 at https://github.com/pfreguia/nuki.homey/tree/v3.0.4.
