### ISSUE TITLE
Opener Doorbell flow not working right ?

### ISSUE THREAD

**Issue by Strike2001** [jghaanstra/nuki.homey#15]
hi when you make a flow with the condition : 
If:
floor motion detection active 
And:
The doorbell rang less than 5 seconds ago
then: 
do anything . 

is not working 

the doorbell rang more than x seconds ago
works . but this works anytime it can be ring days before  when you can not set the less seconds in a condition. 

example 
when:
- floor motion detector is active

and:
- RingToOpen is unlocked 
- The doorbell rang for more then 5 deconds
- The doorbell rang for less then 300 
   seconds ago

then: 
- open nuki smartlock after 15 seconds.

I used this flow because i must go 2 floors up and the auto unlock function of my nuki smartlock react to fast ( on the way to the 1 floor it  starts open door . when i arrived the 2 floor the door was already opened and now closed . 

I missed an option in the nuki app where you can set a time for : smartlock detected user autounlock after x seconds . when the way is to long after bluetooth detected phone .auto unlock of smartlock is unusable for this people .  
or  maybe the way from street over garden to the door is long enough same thing

with this conditions of your app (when they worked right ) i can solve this problem . 
please look at this error . 
and thanks for the great work. 

by the way another question: 
is it possible to set the doorbell signal off with the api ? so if you can set a time  for  doorbell is inactive (Nightmode) ?

**Comment by Strike2001** [comment]
![575F9E41-B31C-4D90-AFCE-45EAA576C90E](https://user-images.githubusercontent.com/5000021/97783896-f8eb0f00-1b9a-11eb-8236-5d601b9fd829.png)

**Comment by pfreguia** [comment]
Yes, you are right. There is a bug I resolved in v 3.0.6. Nuki Direct v3.0.6 will be released today.
Thanks for the error report.

**Comment by Strike2001** [comment]
i can spend you some money for your great app ? i think thats a minimum for this awesome work .
