### ISSUE TITLE
✖ Homey App did not validate id "nuki_state_changed",

### ISSUE THREAD

**Issue by dadalouis** [jghaanstra/nuki.homey#17]
✖ Homey App did not validate against level `debug`:
Found multiple Flow card triggers with the id "nuki_state_changed", all Flow cards should have a unique id.
can you help with that ?

**Comment by mirko3000** [comment]
Same for me here. Tried uninstalling the original nuki app, did not solve the issue...

**Comment by mirko3000** [comment]
I created a PR to fix this issue, the "nuki_state_changed" flow was used both for Nuki and Opener, I renamed the Opener and also did some further fixes to the Opener config.

**Comment by pfreguia** [comment]
Hello dadalouis,
I corrected the code to comply with latest Homey Apps SDK v3 rules and guidelines.
I committed my changes right now. I'll release soon a new version of Nuki Direct.

Best Regards
