### ISSUE TITLE
Support for Nuki Smart Lock 3.0 Pro with built-in wifi?

### ISSUE THREAD

**Issue by KossikCZ** [jghaanstra/nuki.homey#18]
Hello,
I have bought both Nuki 3.0 Pro smart lock and Homey Pro just recently, with a huge hopes to integrate that all along with my other IoT (Xiaomi, Tuya, Netatmo, ..) into a single environment.
However with Nuki I can't get that working in any way, not with the official app from Athom neither with yours. Is there a chance to have this smart lock supported by your application as well please? Thank you very much in advance.

**Comment by pfreguia** [comment]
Hello KossikCZ,
I updated the code in order to support also Nuki Smart Lock 3.0 (Pro).
I committed my changes right now. I'll release soon a new version of Nuki Direct.

Best Regards
