### ISSUE TITLE
[Feature request] Manual entry of bridge IP adress during pairing

### ISSUE THREAD

**Issue by Gand41f** [jghaanstra/nuki.homey#2]
As stated [here](https://community.athom.com/t/app-nuki-bridge-api-not-in-app-store/10853/88?u=g4nd41f) the app does not work when using a software/smartphone bridge. Therefore I would appreciate being able to manually enter the IP adress of the bridge during the pairing process.

**Comment by jghaanstra** [comment]
Does the software bridge have this information available inside the app?

* IP address
* Port
* Token
* nukiId

This is the information needed to manually add a bridge but I'm wondering if users have access to this information easily.

**Comment by jghaanstra** [comment]
Try the latest version in the master branch. It should give you the option to manually pair your Nuki bridge if the discovery returns no results. Let me know if it works for you.

**Comment by Gand41f** [comment]
> 
> 
> Does the software bridge have this information available inside the app?
> 
>     * IP address
> 
>     * Port
> 
>     * Token
> 
>     * nukiId
> 
> 
> This is the information needed to manually add a bridge but I'm wondering if users have access to this information easily.

Yes, all that information is displayed in the bridge app.

**Comment by Gand41f** [comment]
Thank you very much for the fast response. I did install the latest version (1.2.0). However, when adding a new lock, it did not show me any option to enter anything, but went straight to the error "request to "http://undefinded/:undefinded/auth failed, reason: getaddrinfo ENOTFOUND undefined undefined:80" after clicking on the install button. Hereafter I can only click on the close button.

**Comment by jghaanstra** [comment]
Hmmm, I'll look into that. Might take some time though.

**Comment by jghaanstra** [comment]
> Thank you very much for the fast response. I did install the latest version (1.2.0). However, when adding a new lock, it did not show me any option to enter anything, but went straight to the error "request to "http://undefinded/:undefinded/auth failed, reason: getaddrinfo ENOTFOUND undefined undefined:80" after clicking on the install button. Hereafter I can only click on the close button.

Can you tell me what this link returns on your home network?

https://api.nuki.io/discover/bridges

**Comment by Gand41f** [comment]
It does show the bridge, but only with id and dateupdated. IP and port number are missing. 

See also: https://developer.nuki.io/t/no-ip-despite-activate-http-api-in-discovery/5843

**Comment by jghaanstra** [comment]
Could you post the exact output (with you nukiID removed).

**Comment by Gand41f** [comment]
{"bridges":[{"bridgeId":xxx,"dateUpdated":"2020-05-18T15:34:37Z"}],"errorCode":0}

**Comment by jghaanstra** [comment]
Can you try again with the lastest version in master branch.

**Comment by Gand41f** [comment]
Works like a charm :). Thanks a lot. Can I buy you a beer?

**Comment by jghaanstra** [comment]
Great!

Beers are always welcome: https://www.paypal.me/jghaanstra

**Comment by jghaanstra** [comment]
Thanx for the donation, much appreciated .. 🍻
