### ISSUE TITLE
Smartlocks not found during paring, Opener works

### ISSUE THREAD

**Issue by Gand41f** [jghaanstra/nuki.homey#23]
I have a Nuki Opener and a Nuki Smartlock 1.0 and 3.0. I installed version 3.10.0 of Nuki direct via CLI. When searching for new openers I can pair my Nuki Opener. However, both smartlocks cannot be found, despite beeing paired with my bridge. When searching for a lock it shows that no new devices were found.

The bridge has firmware version 2.14.0, the Opener 1.8.1, Smartlock 1 1.14.1, the Smartlock 3 3.3.5.

Any ideas what I am doing wrong or is this a bug?

**Comment by pfreguia** [comment]
Hello @Gand41f,
Please, enter the following URL on a browser of a PC that is connected to the same local network as Homey (replacing the three placeholders with the appropriate values):
`http://<LocalIP>:<LocalPort>/list?token=<YourToken>`
The output should be similar to the following:

```
[
  {
    "deviceType": 0,
    "nukiId": ........,
    "name": "........",
    "firmwareVersion": "1.1.14",
    "lastKnownState": {
      "mode": 2,
      "state": 3,
      "stateName": "unlocked",
      "batteryCritical": false,
      "batteryCharging": false,
      "batteryChargeState": 68,
      "keypadBatteryCritical": false,
      "doorsensorState": 2,
      "doorsensorStateName": "door closed",
      "timestamp": "2022-08-16T11:08:22+00:00"
    }
  },
  {
    "deviceType": 2,
    "nukiId": ........,
    "name": "........",
    "firmwareVersion": "1.8.1",
    "lastKnownState": {
      "mode": 2,
      "state": 1,
      "stateName": "online",
      "batteryCritical": false,
      "ringactionTimestamp": "2022-08-16T08:11:03+00:00",
      "ringactionState": false,
      "timestamp": "2022-08-16T10:20:29+00:00"
    }
  },
  {
    "deviceType": 4,
    "nukiId": ........,
    "name": "........",
    "firmwareVersion": "3.3.5",
    "lastKnownState": {
      "mode": 2,
      "state": 3,
      "stateName": "unlocked",
      "batteryCritical": false,
      "batteryCharging": false,
      "batteryChargeState": 90,
      "keypadBatteryCritical": false,
      "doorsensorState": 2,
      "doorsensorStateName": "door closed",
      "timestamp": "2022-08-16T10:20:31+00:00"
    }
  }
]
```

The deviceType 0 is SmartLock 1.0, the deviceType 2 is Opener, the deviceType 4 is SmartLock 3.0.

Please, send me the output of the command.

Thank you

**Comment by Gand41f** [comment]
This is the response:

`[{"deviceType": 4, "nukiId": ***, "name": "Wohnungstür"}, {"deviceType": 2, "nukiId": ***, "name": "Haustür"}, {"deviceType": 0, "nukiId": ***, "name": "Zuhause "}]`

The real nukiID was replace with ***.

**Comment by pfreguia** [comment]
Hello @Gand41f,
I resolved the issue. A new version of Nuki Direct (v3.1.1) that resolves the issue is available on this repository.
Thank you
