### ISSUE TITLE
Timeout when adding a new device

### ISSUE THREAD

**Issue by Gand41f** [jghaanstra/nuki.homey#3]
When adding a new device (opener or lock) I get the error "Timed out after 30000ms". I now use the hardware bridge with Firmware 2.5.2, an Opener with 1.4.9 and a lock with 1.9.6. Calling https://api.nuki.io/discover/bridges gives me:

"
{"bridges":[{"bridgeId":xxx,"ip":"192.168.178.138","port":8080,"dateUpdated":"2020-07-10T06:40:13Z"}],"errorCode":0}

where I replaced the acutal bridge ID with xxx.

I am using verison 1.3.0 of the app. Before installing it, I did uninstall the old app and deleted all devices. The http API is activated on the bridge.

**Comment by jghaanstra** [comment]
Did you push the button on the bridge during pairing? Is the IP 192.168.178.138 accessable for Homey (in case of VLANs for instance)? Did you try `homey app run` to see if there is extra logging there?

**Comment by Gand41f** [comment]
I did not push the button. Wasn't aware of that. Maybe you include a message ;)

Now it works.

**Comment by jghaanstra** [comment]
It's already in the installation instruction.
