### ISSUE TITLE
Tested 3.0.3 

### ISSUE THREAD

**Issue by chrisboer** [jghaanstra/nuki.homey#6]
Action item will open the door and 3x done and works without an issue.

But after locking the door and then open the door I get a timeout issue. 

Also locking and unlocking give a timeout issue and give status device is not available.

**Comment by pfreguia** [comment]
Electromechanical actions such as Unlock and Lock, take time to actuate (from a few seconds to a few tens of seconds for the Lock ‘n’ Go). Therefore, it may occur that an action (from user interface or from an action flow) starts when another action is already in progress.
Previous versions of Nuki Direct did not handle explicitly overlapping actions and this could lead to unexpected behaviors.
Version v.3.0.4 applies the following rules to overlapping actions (i.e.: action B starts before the action A is finished). RULE 1: If action B is the same as action A (for example: B is a Lock action in progress and A is also a Lock action) then action B simply waits for the completion of A and return success. RULE 2: If action B is different from action A (for example: A is a Lock action in progress and B is an Open/Unlatch action) then action B is rejected. The action flow card "Nuki action" provides a new setting that optionally enables the following RULE 3: If the action B defined in the flow card is different from action A (same as RULE 2) then the flow card defers the execution of action B after the completion of action A.
These rules also apply to more than two actions.
